package com.tony.downloadlib.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tony.downloadlib.model.DownloadModel;

import com.tony.downloadlib.greendao.DownloadModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadModelDaoConfig;

    private final DownloadModelDao downloadModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadModelDaoConfig = daoConfigMap.get(DownloadModelDao.class).clone();
        downloadModelDaoConfig.initIdentityScope(type);

        downloadModelDao = new DownloadModelDao(downloadModelDaoConfig, this);

        registerDao(DownloadModel.class, downloadModelDao);
    }
    
    public void clear() {
        downloadModelDaoConfig.getIdentityScope().clear();
    }

    public DownloadModelDao getDownloadModelDao() {
        return downloadModelDao;
    }

}
